const streamersData = [
  {
    "id": 1,
    "nom": "Ninja",
    "pseudo": "Ninja",
    "plateforme": "Twitch",
    "abonnes": 18500000,
    "viewers": 45000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Joueur professionnel de Fortnite, connu pour ses streams énergiques.",
    "avatar": "🥷"
  },
  {
    "id": 2,
    "nom": "Squeezie",
    "pseudo": "Squeezie",
    "plateforme": "Twitch",
    "abonnes": 8200000,
    "viewers": 120000,
    "categorie": "Variété",
    "pays": "France",
    "description": "YouTubeur et streamer français, créateur du GP Explorer.",
    "avatar": "🎮"
  },
  {
    "id": 3,
    "nom": "Pokimane",
    "pseudo": "Pokimane",
    "plateforme": "Twitch",
    "abonnes": 9300000,
    "viewers": 25000,
    "categorie": "Just Chatting",
    "pays": "Canada",
    "description": "Streameuse populaire connue pour ses streams de discussion.",
    "avatar": "💜"
  },
  {
    "id": 4,
    "nom": "Gotaga",
    "pseudo": "Gotaga",
    "plateforme": "Twitch",
    "abonnes": 4500000,
    "viewers": 35000,
    "categorie": "FPS",
    "pays": "France",
    "description": "Champion du monde Call of Duty, streamer gaming.",
    "avatar": "🎯"
  },
  {
    "id": 5,
    "nom": "xQc",
    "pseudo": "xQcOW",
    "plateforme": "Kick",
    "abonnes": 12000000,
    "viewers": 80000,
    "categorie": "Variété",
    "pays": "Canada",
    "description": "Ex-joueur pro Overwatch, connu pour ses réactions.",
    "avatar": "⚡"
  },
  {
    "id": 6,
    "nom": "Sardoche",
    "pseudo": "Sardoche",
    "plateforme": "Twitch",
    "abonnes": 1800000,
    "viewers": 15000,
    "categorie": "League of Legends",
    "pays": "France",
    "description": "Streamer français spécialisé League of Legends.",
    "avatar": "🦁"
  },
  {
    "id": 7,
    "nom": "Amouranth",
    "pseudo": "Amouranth",
    "plateforme": "Twitch",
    "abonnes": 6200000,
    "viewers": 12000,
    "categorie": "Just Chatting",
    "pays": "États-Unis",
    "description": "Streameuse et entrepreneuse américaine.",
    "avatar": "🌸"
  },
  {
    "id": 8,
    "nom": "Kamet0",
    "pseudo": "Kamet0",
    "plateforme": "Twitch",
    "abonnes": 2100000,
    "viewers": 18000,
    "categorie": "League of Legends",
    "pays": "France",
    "description": "Streamer français, duo légendaire avec Sardoche.",
    "avatar": "🐉"
  },
  {
    "id": 9,
    "nom": "Shroud",
    "pseudo": "shroud",
    "plateforme": "Twitch",
    "abonnes": 11000000,
    "viewers": 55000,
    "categorie": "FPS",
    "pays": "Canada",
    "description": "Ancien joueur professionnel CS:GO, maintenant streamer FPS.",
    "avatar": "🎪"
  },
  {
    "id": 10,
    "nom": "Asmongold",
    "pseudo": "Asmongold",
    "plateforme": "Twitch",
    "abonnes": 3500000,
    "viewers": 90000,
    "categorie": "MMORPG",
    "pays": "États-Unis",
    "description": "Streamer spécialisé dans World of Warcraft et les MMORPG.",
    "avatar": "⚔️"
  },
  {
    "id": 11,
    "nom": "Ibai",
    "pseudo": "Ibai",
    "plateforme": "Twitch",
    "abonnes": 15000000,
    "viewers": 200000,
    "categorie": "Variété",
    "pays": "Espagne",
    "description": "Streamer espagnol très populaire, organisateur d'événements.",
    "avatar": "🔥"
  },
  {
    "id": 12,
    "nom": "Rubius",
    "pseudo": "Rubius",
    "plateforme": "YouTube",
    "abonnes": 41000000,
    "viewers": 85000,
    "categorie": "Gaming",
    "pays": "Espagne",
    "description": "YouTuber et streamer espagnol, l'un des plus suivis au monde.",
    "avatar": "👾"
  },
  {
    "id": 13,
    "nom": "Auronplay",
    "pseudo": "Auronplay",
    "plateforme": "Twitch",
    "abonnes": 3000000,
    "viewers": 75000,
    "categorie": "Variété",
    "pays": "Espagne",
    "description": "Streamer espagnol connu pour son humour et ses réactions.",
    "avatar": "😎"
  },
  {
    "id": 14,
    "nom": "Myth",
    "pseudo": "TSM_Myth",
    "plateforme": "Twitch",
    "abonnes": 4800000,
    "viewers": 28000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Joueur professionnel de Fortnite, membre de TSM.",
    "avatar": "🏹"
  },
  {
    "id": 15,
    "nom": "TimTheTatman",
    "pseudo": "TimTheTatman",
    "plateforme": "YouTube",
    "abonnes": 5500000,
    "viewers": 42000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Streamer populaire connu pour ses streams de Call of Duty et Warzone.",
    "avatar": "🎲"
  },
  {
    "id": 16,
    "nom": "DrDisrespect",
    "pseudo": "DrDisrespect",
    "plateforme": "YouTube",
    "abonnes": 4800000,
    "viewers": 65000,
    "categorie": "FPS",
    "pays": "États-Unis",
    "description": "Personnage iconique du streaming FPS, connu pour son style unique.",
    "avatar": "🎭"
  },
  {
    "id": 17,
    "nom": "Valkyrae",
    "pseudo": "Valkyrae",
    "plateforme": "YouTube",
    "abonnes": 4200000,
    "viewers": 38000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Streamer populaire, membre de 100 Thieves.",
    "avatar": "👑"
  },
  {
    "id": 18,
    "nom": "Sykkuno",
    "pseudo": "Sykkuno",
    "plateforme": "YouTube",
    "abonnes": 3800000,
    "viewers": 32000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Streamer connu pour ses streams Among Us et ses collaborations.",
    "avatar": "😊"
  },
  {
    "id": 19,
    "nom": "Ludwig",
    "pseudo": "Ludwig",
    "plateforme": "YouTube",
    "abonnes": 5200000,
    "viewers": 45000,
    "categorie": "Variété",
    "pays": "États-Unis",
    "description": "Streamer créatif connu pour ses événements et défis uniques.",
    "avatar": "🎪"
  },
  {
    "id": 20,
    "nom": "HasanAbi",
    "pseudo": "HasanAbi",
    "plateforme": "Twitch",
    "abonnes": 2800000,
    "viewers": 55000,
    "categorie": "Just Chatting",
    "pays": "États-Unis",
    "description": "Streamer politique et commentateur, connu pour ses analyses.",
    "avatar": "📺"
  },
  {
    "id": 21,
    "nom": "Kai Cenat",
    "pseudo": "KaiCenat",
    "plateforme": "Twitch",
    "abonnes": 12000000,
    "viewers": 180000,
    "categorie": "Variété",
    "pays": "États-Unis",
    "description": "Streamer très populaire connu pour son énergie et son contenu varié.",
    "avatar": "💥"
  },
  {
    "id": 22,
    "nom": "Tfue",
    "pseudo": "Tfue",
    "plateforme": "Kick",
    "abonnes": 11000000,
    "viewers": 48000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Joueur professionnel de Fortnite, l'un des meilleurs au monde.",
    "avatar": "🎯"
  },
  {
    "id": 23,
    "nom": "Bugha",
    "pseudo": "Bugha",
    "plateforme": "Twitch",
    "abonnes": 3200000,
    "viewers": 22000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Champion du monde Fortnite World Cup 2019.",
    "avatar": "🏆"
  },
  {
    "id": 24,
    "nom": "Clix",
    "pseudo": "Clix",
    "plateforme": "Kick",
    "abonnes": 4500000,
    "viewers": 35000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Joueur professionnel de Fortnite, connu pour ses skills.",
    "avatar": "⚡"
  },
  {
    "id": 25,
    "nom": "SypherPK",
    "pseudo": "SypherPK",
    "plateforme": "Twitch",
    "abonnes": 5200000,
    "viewers": 28000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Streamer éducatif Fortnite, connu pour ses guides et tutoriels.",
    "avatar": "📚"
  },
  {
    "id": 26,
    "nom": "Nickmercs",
    "pseudo": "Nickmercs",
    "plateforme": "Kick",
    "abonnes": 6800000,
    "viewers": 52000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Streamer populaire, ancien joueur professionnel Call of Duty.",
    "avatar": "💪"
  },
  {
    "id": 27,
    "nom": "Scump",
    "pseudo": "Scump",
    "plateforme": "YouTube",
    "abonnes": 3200000,
    "viewers": 25000,
    "categorie": "FPS",
    "pays": "États-Unis",
    "description": "Légende du Call of Duty, membre d'OpTic Gaming.",
    "avatar": "🎖️"
  },
  {
    "id": 28,
    "nom": "Summit1g",
    "pseudo": "summit1g",
    "plateforme": "Twitch",
    "abonnes": 6200000,
    "viewers": 38000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Vétéran du streaming, connu pour ses streams variés.",
    "avatar": "🎮"
  },
  {
    "id": 29,
    "nom": "Lirik",
    "pseudo": "Lirik",
    "plateforme": "Twitch",
    "abonnes": 3800000,
    "viewers": 32000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Streamer variété, connu pour ses streams de différents jeux.",
    "avatar": "🎲"
  },
  {
    "id": 30,
    "nom": "MoistCr1TiKaL",
    "pseudo": "MoistCr1TiKaL",
    "plateforme": "YouTube",
    "abonnes": 15000000,
    "viewers": 85000,
    "categorie": "Variété",
    "pays": "États-Unis",
    "description": "Créateur de contenu populaire, connu pour ses critiques et réactions.",
    "avatar": "💧"
  },
  {
    "id": 31,
    "nom": "xQc",
    "pseudo": "xQc",
    "plateforme": "Twitch",
    "abonnes": 12000000,
    "viewers": 95000,
    "categorie": "Variété",
    "pays": "Canada",
    "description": "Streamer très populaire, connu pour ses réactions et son contenu varié.",
    "avatar": "⚡"
  },
  {
    "id": 32,
    "nom": "Mizkif",
    "pseudo": "Mizkif",
    "plateforme": "Twitch",
    "abonnes": 1800000,
    "viewers": 28000,
    "categorie": "Just Chatting",
    "pays": "États-Unis",
    "description": "Streamer connu pour ses événements et collaborations.",
    "avatar": "🐱"
  },
  {
    "id": 33,
    "nom": "Sodapoppin",
    "pseudo": "Sodapoppin",
    "plateforme": "Twitch",
    "abonnes": 3200000,
    "viewers": 25000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Vétéran du streaming, l'un des premiers grands streamers.",
    "avatar": "🥤"
  },
  {
    "id": 34,
    "nom": "Trainwreckstv",
    "pseudo": "Trainwreckstv",
    "plateforme": "Kick",
    "abonnes": 2800000,
    "viewers": 45000,
    "categorie": "Gambling",
    "pays": "États-Unis",
    "description": "Streamer connu pour ses streams de casino et gambling.",
    "avatar": "🎰"
  },
  {
    "id": 35,
    "nom": "Adin Ross",
    "pseudo": "AdinRoss",
    "plateforme": "Kick",
    "abonnes": 8500000,
    "viewers": 120000,
    "categorie": "Just Chatting",
    "pays": "États-Unis",
    "description": "Streamer populaire connu pour ses interviews et collaborations.",
    "avatar": "🎤"
  },
  {
    "id": 36,
    "nom": "IshowSpeed",
    "pseudo": "IshowSpeed",
    "plateforme": "YouTube",
    "abonnes": 25000000,
    "viewers": 150000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Streamer très énergique, connu pour ses réactions et son contenu football.",
    "avatar": "⚽"
  },
  {
    "id": 37,
    "nom": "Dream",
    "pseudo": "Dream",
    "plateforme": "YouTube",
    "abonnes": 32000000,
    "viewers": 95000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Créateur Minecraft très populaire, connu pour ses speedruns.",
    "avatar": "😊"
  },
  {
    "id": 38,
    "nom": "PewDiePie",
    "pseudo": "PewDiePie",
    "plateforme": "YouTube",
    "abonnes": 111000000,
    "viewers": 45000,
    "categorie": "Gaming",
    "pays": "Suède",
    "description": "Légende de YouTube, l'un des créateurs les plus suivis au monde.",
    "avatar": "👑"
  },
  {
    "id": 39,
    "nom": "Markiplier",
    "pseudo": "Markiplier",
    "plateforme": "YouTube",
    "abonnes": 38000000,
    "viewers": 55000,
    "categorie": "Gaming",
    "pays": "États-Unis",
    "description": "Créateur de contenu gaming très populaire, connu pour ses réactions.",
    "avatar": "🎭"
  },
  {
    "id": 40,
    "nom": "Jacksepticeye",
    "pseudo": "jacksepticeye",
    "plateforme": "YouTube",
    "abonnes": 32000000,
    "viewers": 42000,
    "categorie": "Gaming",
    "pays": "Irlande",
    "description": "Créateur de contenu gaming irlandais très énergique.",
    "avatar": "☘️"
  },
  {
    "id": 41,
    "nom": "MrBeast",
    "pseudo": "MrBeast",
    "plateforme": "YouTube",
    "abonnes": 250000000,
    "viewers": 180000,
    "categorie": "Variété",
    "pays": "États-Unis",
    "description": "Créateur de contenu le plus suivi au monde, connu pour ses défis et générosité.",
    "avatar": "💰"
  },
  {
    "id": 42,
    "nom": "Félix Lengyel",
    "pseudo": "xQc",
    "plateforme": "Kick",
    "abonnes": 12000000,
    "viewers": 85000,
    "categorie": "Variété",
    "pays": "Canada",
    "description": "Streamer québécois très populaire, ancien joueur pro Overwatch.",
    "avatar": "🍁"
  },
  {
    "id": 43,
    "nom": "Alphacast",
    "pseudo": "Alphacast",
    "plateforme": "Twitch",
    "abonnes": 850000,
    "viewers": 12000,
    "categorie": "League of Legends",
    "pays": "France",
    "description": "Caster et analyste League of Legends français.",
    "avatar": "🎙️"
  },
  {
    "id": 44,
    "nom": "Solary",
    "pseudo": "Solary",
    "plateforme": "Twitch",
    "abonnes": 1200000,
    "viewers": 18000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Organisation esport française, chaîne principale.",
    "avatar": "⭐"
  },
  {
    "id": 45,
    "nom": "Doigby",
    "pseudo": "Doigby",
    "plateforme": "Twitch",
    "abonnes": 420000,
    "viewers": 8500,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français spécialisé dans les jeux indés.",
    "avatar": "🎨"
  },
  {
    "id": 46,
    "nom": "MisterMV",
    "pseudo": "MisterMV",
    "plateforme": "Twitch",
    "abonnes": 2800000,
    "viewers": 32000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français très populaire, connu pour ses streams variés.",
    "avatar": "🎮"
  },
  {
    "id": 47,
    "nom": "Ponce",
    "pseudo": "Ponce",
    "plateforme": "Twitch",
    "abonnes": 1800000,
    "viewers": 22000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français, membre de Solary.",
    "avatar": "🦄"
  },
  {
    "id": 48,
    "nom": "Locklear",
    "pseudo": "Locklear",
    "plateforme": "Twitch",
    "abonnes": 950000,
    "viewers": 15000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français spécialisé dans les jeux compétitifs.",
    "avatar": "🔒"
  },
  {
    "id": 49,
    "nom": "ZeratoR",
    "pseudo": "ZeratoR",
    "plateforme": "Twitch",
    "abonnes": 2200000,
    "viewers": 28000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français, organisateur d'événements esport.",
    "avatar": "⚡"
  },
  {
    "id": 50,
    "nom": "JLTomy",
    "pseudo": "JLTomy",
    "plateforme": "Twitch",
    "abonnes": 650000,
    "viewers": 12000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français, connu pour ses streams de jeux variés.",
    "avatar": "🎯"
  },
  {
    "id": 51,
    "nom": "KennyStream",
    "pseudo": "KennyStream",
    "plateforme": "Twitch",
    "abonnes": 480000,
    "viewers": 9500,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français spécialisé dans les jeux de stratégie.",
    "avatar": "🧠"
  },
  {
    "id": 52,
    "nom": "Antoine Daniel",
    "pseudo": "AntoineDaniel",
    "plateforme": "Twitch",
    "abonnes": 1500000,
    "viewers": 18000,
    "categorie": "Variété",
    "pays": "France",
    "description": "Créateur de contenu français, connu pour WTC et ses analyses.",
    "avatar": "📺"
  },
  {
    "id": 53,
    "nom": "Joueur du Grenier",
    "pseudo": "JoueurDuGrenier",
    "plateforme": "YouTube",
    "abonnes": 3200000,
    "viewers": 25000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Créateur de contenu gaming français, connu pour ses critiques de jeux rétro.",
    "avatar": "🎮"
  },
  {
    "id": 54,
    "nom": "Amixem",
    "pseudo": "Amixem",
    "plateforme": "YouTube",
    "abonnes": 4200000,
    "viewers": 32000,
    "categorie": "Variété",
    "pays": "France",
    "description": "YouTuber français très populaire, créateur de contenu varié.",
    "avatar": "🎬"
  },
  {
    "id": 55,
    "nom": "Mcfly et Carlito",
    "pseudo": "McflyCarlito",
    "plateforme": "YouTube",
    "abonnes": 8500000,
    "viewers": 55000,
    "categorie": "Variété",
    "pays": "France",
    "description": "Duo de YouTubers français très populaire, créateurs de sketches.",
    "avatar": "🎭"
  },
  {
    "id": 56,
    "nom": "Cyprien",
    "pseudo": "Cyprien",
    "plateforme": "YouTube",
    "abonnes": 14000000,
    "viewers": 45000,
    "categorie": "Variété",
    "pays": "France",
    "description": "YouTuber français légendaire, l'un des premiers créateurs français.",
    "avatar": "🎪"
  },
  {
    "id": 57,
    "nom": "Norman",
    "pseudo": "Normanfaitdesvidéos",
    "plateforme": "YouTube",
    "abonnes": 12000000,
    "viewers": 38000,
    "categorie": "Variété",
    "pays": "France",
    "description": "YouTuber français très populaire, créateur de sketches humoristiques.",
    "avatar": "😄"
  },
  {
    "id": 58,
    "nom": "Natoo",
    "pseudo": "Natoo",
    "plateforme": "YouTube",
    "abonnes": 3200000,
    "viewers": 22000,
    "categorie": "Variété",
    "pays": "France",
    "description": "YouTuber française très populaire, créatrice de contenu humoristique.",
    "avatar": "💃"
  },
  {
    "id": 59,
    "nom": "EnjoyPhoenix",
    "pseudo": "EnjoyPhoenix",
    "plateforme": "YouTube",
    "abonnes": 2800000,
    "viewers": 18000,
    "categorie": "Lifestyle",
    "pays": "France",
    "description": "YouTuber française, créatrice de contenu lifestyle et beauté.",
    "avatar": "✨"
  },
  {
    "id": 60,
    "nom": "Lena Situations",
    "pseudo": "LenaSituations",
    "plateforme": "YouTube",
    "abonnes": 1800000,
    "viewers": 15000,
    "categorie": "Lifestyle",
    "pays": "France",
    "description": "Créatrice de contenu française, spécialisée dans le lifestyle.",
    "avatar": "🌸"
  },
  {
    "id": 61,
    "nom": "Tibo InShape",
    "pseudo": "TiboInShape",
    "plateforme": "YouTube",
    "abonnes": 8500000,
    "viewers": 65000,
    "categorie": "Sport",
    "pays": "France",
    "description": "Créateur de contenu fitness français très populaire.",
    "avatar": "💪"
  },
  {
    "id": 62,
    "nom": "Seb",
    "pseudo": "Seb",
    "plateforme": "Twitch",
    "abonnes": 1200000,
    "viewers": 20000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français, membre de Solary.",
    "avatar": "🎮"
  },
  {
    "id": 63,
    "nom": "Etoiles",
    "pseudo": "Etoiles",
    "plateforme": "Twitch",
    "abonnes": 850000,
    "viewers": 15000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français spécialisé dans les jeux compétitifs.",
    "avatar": "⭐"
  },
  {
    "id": 64,
    "nom": "Baghera Jones",
    "pseudo": "BagheraJones",
    "plateforme": "Twitch",
    "abonnes": 650000,
    "viewers": 12000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer française spécialisée dans les jeux de rôle.",
    "avatar": "🎲"
  },
  {
    "id": 65,
    "nom": "Aypierre",
    "pseudo": "Aypierre",
    "plateforme": "Twitch",
    "abonnes": 480000,
    "viewers": 9500,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français spécialisé dans Minecraft.",
    "avatar": "⛏️"
  },
  {
    "id": 66,
    "nom": "Aurelien Sama",
    "pseudo": "AurelienSama",
    "plateforme": "Twitch",
    "abonnes": 320000,
    "viewers": 7500,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français, créateur de contenu gaming.",
    "avatar": "🎯"
  },
  {
    "id": 67,
    "nom": "Bibi",
    "pseudo": "Bibi",
    "plateforme": "Twitch",
    "abonnes": 280000,
    "viewers": 6500,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français spécialisé dans les jeux indés.",
    "avatar": "🎨"
  },
  {
    "id": 68,
    "nom": "Chapix",
    "pseudo": "Chapix",
    "plateforme": "Twitch",
    "abonnes": 420000,
    "viewers": 8500,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français, membre de Solary.",
    "avatar": "🦊"
  },
  {
    "id": 69,
    "nom": "Domingo",
    "pseudo": "Domingo",
    "plateforme": "Twitch",
    "abonnes": 380000,
    "viewers": 8000,
    "categorie": "Gaming",
    "pays": "France",
    "description": "Streamer français spécialisé dans les jeux de stratégie.",
    "avatar": "🎪"
  },
  {
    "id": 70,
    "nom": "Faker",
    "pseudo": "Faker",
    "plateforme": "Twitch",
    "abonnes": 5500000,
    "viewers": 85000,
    "categorie": "League of Legends",
    "pays": "Corée du Sud",
    "description": "Légende de League of Legends, considéré comme le meilleur joueur de tous les temps.",
    "avatar": "👑"
  },
  {
    "id": 71,
    "nom": "Uzi",
    "pseudo": "Uzi",
    "plateforme": "Twitch",
    "abonnes": 3200000,
    "viewers": 45000,
    "categorie": "League of Legends",
    "pays": "Chine",
    "description": "Joueur professionnel League of Legends chinois, légende de l'ADC.",
    "avatar": "🎯"
  },
  {
    "id": 72,
    "nom": "Caps",
    "pseudo": "Caps",
    "plateforme": "Twitch",
    "abonnes": 1800000,
    "viewers": 28000,
    "categorie": "League of Legends",
    "pays": "Danemark",
    "description": "Joueur professionnel League of Legends, membre de G2 Esports.",
    "avatar": "⚡"
  },
  {
    "id": 73,
    "nom": "Doublelift",
    "pseudo": "Doublelift",
    "plateforme": "Twitch",
    "abonnes": 2200000,
    "viewers": 32000,
    "categorie": "League of Legends",
    "pays": "États-Unis",
    "description": "Légende de League of Legends en Amérique du Nord.",
    "avatar": "🏆"
  },
  {
    "id": 74,
    "nom": "Bjergsen",
    "pseudo": "Bjergsen",
    "plateforme": "Twitch",
    "abonnes": 2800000,
    "viewers": 35000,
    "categorie": "League of Legends",
    "pays": "Danemark",
    "description": "Ancien joueur professionnel League of Legends, maintenant coach.",
    "avatar": "🎮"
  },
  {
    "id": 75,
    "nom": "Perkz",
    "pseudo": "Perkz",
    "plateforme": "Twitch",
    "abonnes": 1500000,
    "viewers": 22000,
    "categorie": "League of Legends",
    "pays": "Croatie",
    "description": "Joueur professionnel League of Legends, membre de G2 Esports.",
    "avatar": "⚔️"
  },
  {
    "id": 76,
    "nom": "Rekkles",
    "pseudo": "Rekkles",
    "plateforme": "Twitch",
    "abonnes": 1800000,
    "viewers": 25000,
    "categorie": "League of Legends",
    "pays": "Suède",
    "description": "Joueur professionnel League of Legends européen.",
    "avatar": "🎯"
  },
  {
    "id": 77,
    "nom": "Jankos",
    "pseudo": "Jankos",
    "plateforme": "Twitch",
    "abonnes": 1200000,
    "viewers": 18000,
    "categorie": "League of Legends",
    "pays": "Pologne",
    "description": "Joueur professionnel League of Legends, jungler pour G2 Esports.",
    "avatar": "🌲"
  },
  {
    "id": 78,
    "nom": "Wunder",
    "pseudo": "Wunder",
    "plateforme": "Twitch",
    "abonnes": 850000,
    "viewers": 12000,
    "categorie": "League of Legends",
    "pays": "Danemark",
    "description": "Joueur professionnel League of Legends, top laner.",
    "avatar": "🛡️"
  },
  {
    "id": 79,
    "nom": "Mikyx",
    "pseudo": "Mikyx",
    "plateforme": "Twitch",
    "abonnes": 650000,
    "viewers": 9500,
    "categorie": "League of Legends",
    "pays": "Slovénie",
    "description": "Joueur professionnel League of Legends, support pour G2 Esports.",
    "avatar": "💚"
  },
  {
    "id": 80,
    "nom": "Humanoid",
    "pseudo": "Humanoid",
    "plateforme": "Twitch",
    "abonnes": 480000,
    "viewers": 8000,
    "categorie": "League of Legends",
    "pays": "République tchèque",
    "description": "Joueur professionnel League of Legends, mid laner.",
    "avatar": "🧠"
  },
  {
    "id": 81,
    "nom": "Elyoya",
    "pseudo": "Elyoya",
    "plateforme": "Twitch",
    "abonnes": 550000,
    "viewers": 10000,
    "categorie": "League of Legends",
    "pays": "Espagne",
    "description": "Joueur professionnel League of Legends, jungler pour MAD Lions.",
    "avatar": "🦁"
  },
  {
    "id": 82,
    "nom": "Armut",
    "pseudo": "Armut",
    "plateforme": "Twitch",
    "abonnes": 380000,
    "viewers": 7500,
    "categorie": "League of Legends",
    "pays": "Turquie",
    "description": "Joueur professionnel League of Legends, top laner.",
    "avatar": "🛡️"
  },
  {
    "id": 83,
    "nom": "Carzzy",
    "pseudo": "Carzzy",
    "plateforme": "Twitch",
    "abonnes": 420000,
    "viewers": 8500,
    "categorie": "League of Legends",
    "pays": "République tchèque",
    "description": "Joueur professionnel League of Legends, ADC.",
    "avatar": "🎯"
  },
  {
    "id": 84,
    "nom": "Kaiser",
    "pseudo": "Kaiser",
    "plateforme": "Twitch",
    "abonnes": 350000,
    "viewers": 7000,
    "categorie": "League of Legends",
    "pays": "Allemagne",
    "description": "Joueur professionnel League of Legends, support.",
    "avatar": "💙"
  },
  {
    "id": 85,
    "nom": "Nisqy",
    "pseudo": "Nisqy",
    "plateforme": "Twitch",
    "abonnes": 450000,
    "viewers": 9000,
    "categorie": "League of Legends",
    "pays": "Belgique",
    "description": "Joueur professionnel League of Legends, mid laner.",
    "avatar": "🧙"
  },
  {
    "id": 86,
    "nom": "Razork",
    "pseudo": "Razork",
    "plateforme": "Twitch",
    "abonnes": 400000,
    "viewers": 8000,
    "categorie": "League of Legends",
    "pays": "Espagne",
    "description": "Joueur professionnel League of Legends, jungler.",
    "avatar": "🗡️"
  },
  {
    "id": 87,
    "nom": "Odoamne",
    "pseudo": "Odoamne",
    "plateforme": "Twitch",
    "abonnes": 500000,
    "viewers": 9500,
    "categorie": "League of Legends",
    "pays": "Roumanie",
    "description": "Joueur professionnel League of Legends, top laner vétéran.",
    "avatar": "🛡️"
  },
  {
    "id": 88,
    "nom": "Larssen",
    "pseudo": "Larssen",
    "plateforme": "Twitch",
    "abonnes": 380000,
    "viewers": 7500,
    "categorie": "League of Legends",
    "pays": "Suède",
    "description": "Joueur professionnel League of Legends, mid laner.",
    "avatar": "❄️"
  },
  {
    "id": 89,
    "nom": "Comp",
    "pseudo": "Comp",
    "plateforme": "Twitch",
    "abonnes": 350000,
    "viewers": 7000,
    "categorie": "League of Legends",
    "pays": "Grèce",
    "description": "Joueur professionnel League of Legends, ADC.",
    "avatar": "🏛️"
  },
  {
    "id": 90,
    "nom": "Trymbi",
    "pseudo": "Trymbi",
    "plateforme": "Twitch",
    "abonnes": 320000,
    "viewers": 6500,
    "categorie": "League of Legends",
    "pays": "Pologne",
    "description": "Joueur professionnel League of Legends, support.",
    "avatar": "💫"
  },
  {
    "id": 91,
    "nom": "Malrang",
    "pseudo": "Malrang",
    "plateforme": "Twitch",
    "abonnes": 420000,
    "viewers": 8500,
    "categorie": "League of Legends",
    "pays": "Corée du Sud",
    "description": "Joueur professionnel League of Legends, jungler.",
    "avatar": "🌙"
  },
  {
    "id": 92,
    "nom": "Vetheo",
    "pseudo": "Vetheo",
    "plateforme": "Twitch",
    "abonnes": 380000,
    "viewers": 7500,
    "categorie": "League of Legends",
    "pays": "France",
    "description": "Joueur professionnel League of Legends, mid laner français.",
    "avatar": "⭐"
  },
  {
    "id": 93,
    "nom": "Targamas",
    "pseudo": "Targamas",
    "plateforme": "Twitch",
    "abonnes": 350000,
    "viewers": 7000,
    "categorie": "League of Legends",
    "pays": "Belgique",
    "description": "Joueur professionnel League of Legends, support.",
    "avatar": "🛡️"
  },
  {
    "id": 94,
    "nom": "Flakked",
    "pseudo": "Flakked",
    "plateforme": "Twitch",
    "abonnes": 400000,
    "viewers": 8000,
    "categorie": "League of Legends",
    "pays": "Espagne",
    "description": "Joueur professionnel League of Legends, ADC.",
    "avatar": "🎯"
  },
  {
    "id": 95,
    "nom": "BrokenBlade",
    "pseudo": "BrokenBlade",
    "plateforme": "Twitch",
    "abonnes": 450000,
    "viewers": 9000,
    "categorie": "League of Legends",
    "pays": "Allemagne",
    "description": "Joueur professionnel League of Legends, top laner.",
    "avatar": "⚔️"
  },
  {
    "id": 96,
    "nom": "Yike",
    "pseudo": "Yike",
    "plateforme": "Twitch",
    "abonnes": 480000,
    "viewers": 9000,
    "categorie": "League of Legends",
    "pays": "Suède",
    "description": "Joueur professionnel League of Legends, jungler pour G2 Esports.",
    "avatar": "🌲"
  },
  {
    "id": 97,
    "nom": "Nuc",
    "pseudo": "Nuc",
    "plateforme": "Twitch",
    "abonnes": 320000,
    "viewers": 6500,
    "categorie": "League of Legends",
    "pays": "France",
    "description": "Joueur professionnel League of Legends, mid laner.",
    "avatar": "🧙"
  },
  {
    "id": 98,
    "nom": "Neon",
    "pseudo": "Neon",
    "plateforme": "Twitch",
    "abonnes": 380000,
    "viewers": 7500,
    "categorie": "League of Legends",
    "pays": "République tchèque",
    "description": "Joueur professionnel League of Legends, ADC.",
    "avatar": "💡"
  },
  {
    "id": 99,
    "nom": "Hylissang",
    "pseudo": "Hylissang",
    "plateforme": "Twitch",
    "abonnes": 500000,
    "viewers": 9500,
    "categorie": "League of Legends",
    "pays": "Bulgarie",
    "description": "Joueur professionnel League of Legends, support légendaire.",
    "avatar": "🛡️"
  },
  {
    "id": 100,
    "nom": "Upset",
    "pseudo": "Upset",
    "plateforme": "Twitch",
    "abonnes": 480000,
    "viewers": 9000,
    "categorie": "League of Legends",
    "pays": "Allemagne",
    "description": "Joueur professionnel League of Legends, ADC.",
    "avatar": "⚡"
  }
];
